export default {
    GET_ALL_DEPUTY: 'GET_ALL_DEPUTY',
    GET_DEPUTY_BY_NAME: 'GET_DEPUTY_BY_NAME',
    GET_DEPUTY_BY_ID: 'GET_DEPUTY_BY_ID',
    GET_DEPUTY_PHOTO_BY_ID: 'GET_DEPUTY_PHOTO_BY_ID',
    GET_STAN_OF_DEPUTIES: 'GET_STAN_OF_DEPUTIES',

    SET_ALL_DEPUTY: 'SET_ALL_DEPUTY',
    
}