export default {
    GET_ALL_DEPUTIES: 'GET_ALL_DEPUTIES',
    GET_DEPUTY_BY_NAME: 'GET_DEPUTY_BY_NAME',
    GET_DEPUTY_BY_ID: 'GET_DEPUTY_BY_ID',
    GET_DEPUTY_PHOTO_BY_ID: 'GET_DEPUTY_PHOTO_BY_ID',
    GET_STAN_OF_DEPUTIES: 'GET_STAN_OF_DEPUTIES',

    SET_ALL_DEPUTIES: 'SET_ALL_DEPUTIES',
    SET_FOUND_DEPUTIES: 'SET_FOUND_DEPUTIES',
    SET_SELECTED_DEPUTY: 'SET_SELECTED_DEPUTY',
    SET_STAN_0F_DEPUTIES: 'SET_STAN_0F_DEPUTIES'
}